---
abstract: 'GitHub made me make this'
author:
  - 'brian d foy <bdfoy@cpan.org>'
build_requires:
  ExtUtils::MakeMaker: 0
configure_requires:
  ExtUtils::MakeMaker: 0
dynamic_config: 1
generated_by: 'ExtUtils::MakeMaker version 6.62, CPAN::Meta::Converter version 2.112150'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Psychic-Ninja
no_index:
  directory:
    - t
    - inc
requires:
  Carp: 0
  Mojo::UserAgent: 0
  Test::More: 0.94
  XML::Twig: 0
version: 0.10_02
x_repository: https://github.com/briandfoy/psychic-ninja
